### ISSUE TITLE
Multiple stack instances

### ISSUE THREAD

**Issue by KGuetter** [KNX-IOT/KNX-IOT-STACK#303]
For ETS use, it would be nice if multiple independent instances of the KNX IoT Stack can be used (also in parallel)

Please investigate the options for such an extension.

Suggestion: On the ETS API level, ets_start could return a handle or pointer which is the passed to all other API methods (and the callbacks).

**Comment by WAvdBeek** [comment]
one can start multiple instances in separate processes.
as client one can talk to multiple devices simultaneously
so this change is not needed.
