### ISSUE TITLE
Bind to specific network interface

### ISSUE THREAD

**Issue by KGuetter** [KNX-IOT/KNX-IOT-STACK#304]
Currently the library binds to *all* network interfaces. For ETS, it would be useful to bind to only a specific interface.

Please investigate the options for such an extension.

This is especially useful if also https://github.com/KNX-IOT/KNX-IOT-STACK/issues/303 is implemented.

Suggestion: On the ETS API level, this could be another parameter to the ets_start method (meaning would probably depend on OS)

**Comment by WAvdBeek** [comment]
IPV6 works very differently than IPV4, hence it would be impossible for ETS to know to which interface the messages needs to be send.
Hence this won't be implemented.
